### ISSUE TITLE
Do not include Cake.* in nuget package

### ISSUE THREAD

**Issue by gep13** [cake-contrib/Cake.AliaSql#11]

**Comment by gep13** [comment]
@devlead am I right in saying that it was this package that you mentioned was including Cake.* files in the nuget package?  I don't see that happening.

**Comment by gep13** [comment]
Scratch that, never mind...

**Comment by devlead** [comment]
And I had my red pen ready ;)

![image](https://cloud.githubusercontent.com/assets/1647294/19727649/92cf2cb2-9b90-11e6-9818-460fb4c6994a.png)

XML missing too.

**Comment by gep13** [comment]
The project, as it stands, isn't generating the required XML file either.
