### ISSUE TITLE
Following the Directions on the Homepage of the project doesn't seem to work...

### ISSUE THREAD

**Issue by dcjulian29** [cake-contrib/Cake.AliaSql#6]
`#tool "nuget:?package=AliaSQL"`
`#addin "Cake.AliaSql"`

`var baseDirectory = MakeAbsolute(Directory("."));`
`var databaseServer = ".\\";`
`var databaseName = "ASSESS";`
`var dataDirectory = baseDirectory + "\\data";`
`Task("RebuildDatabase")`
`    .Does(() => `
`    {`
`        AliaSql("Rebuild", new AliaSqlSettings`
`        {`
`            ConnectionString = databaseServer,`
`            DatabaseName = databaseName,`
`            ScriptsFolder = dataDirectory`
`        });`
`    });`

When I run the build, I get an error which Cake is building script.
`The type or namespace name 'AliaSqlSettings' could not be found (are you missing a using directive or an assembly reference?)`

**Comment by RichiCoder1** [comment]
You might have to add `using Cake.AliaSql` at the top after the directives.

**Comment by nelsonwellswku** [comment]
Maybe I'm daft, but I can't get it to work either. I added the #tool and #addin directives and when I ran the script, I got the same error as @dcjulian29 . I added the `using Cake.AliaSql` to the script, but now I'm getting a different error. 

`Error: C:/repo/project/build.cake(51,5): error CS0103: The name 'AliaSql' does not exist in the current context`

`Task("RebuildDatabase")
  .Does(() => {
    AliaSql("Rebuild", new AliaSqlSettings
        {
            ToolPath = "./tools/AliaSQL/tools/AliaSQL.exe",
            ConnectionString = "Data Source=(LocalDb)\v11.0;Initial Catalog=Taurus;Integrated Security=True;",
            DatabaseName = "Nematoad",
            ScriptsFolder = "./src/Migrations/scripts",
        });
  });`

The line number points to the AliaSql line which I copy/pasted into my project. Any ideas?

**Comment by dcjulian29** [comment]
The current version of the addin "0.4.1" is compiled against the "0.6.4" version of Cake. The current version of Cake is 0.14.0 so I think that there must be some breaking change between 0.6.4 and 0.14.0... I created a "private" feed containing a compiled DLL against the 0.14.0 Cake.Core.dll to test the idea, but can't get Cake to load the AddIn from my private feed... I'm currently working around this issue with the following:
```
#tool "nuget:?package=AliaSQL"

Task("RebuildDatabase")
    .Does(() => 
    {
        StartProcess ("tools\\AliaSQL\\tools\\AliaSQL.exe", new ProcessSettings {
            Arguments = "Rebuild " + databaseServer + " " + databaseName + " " + dataDirectory
        });
    });
```

**Comment by nelsonwellswku** [comment]
I put in a PR (#7) to update the project to be built against Cake 0.15.2. There was an obsolete constructor that was being used and apparently it doesn't actually work anymore. Once I updated the constructor to the new one, everything seemed to work correctly.

I'm not sure how to handle the version bumping. @RichiCoder1 , can you review/merge my changes and version bump / package this guy up? Or tell me the steps I should take to do so and I will update my PR.

**Comment by gep13** [comment]
@dcjulian29 @nelsonwellswku a new package version, 0.5.0, has just been pushed to NuGet.org.  Let me know how you get on with it, and if there is anything else you need.  Thanks!

**Comment by dcjulian29** [comment]
Sorry for taking so long to get back to you (@gep13)... I just tested with 0.5.0 from the Nuget.org feed and it works with the current Cake version... Thanks...
