### ISSUE TITLE
Consider making Cake.AliaSql an official cake-contrib package

### ISSUE THREAD

**Issue by nelsonwellswku** [cake-contrib/Cake.AliaSql#8]
This would mean two things:

1. Add cake-contrib as a co-maintainer  to the Nuget package
2. Move the source code to the Cake Contribution Organization repository

As [outlined in the blog post](http://cakebuild.net/blog/2016/08/cake-contribution-organization), this would give more flexibility to the Cake community without changing the primary maintainer.

**Comment by gep13** [comment]
@RichiCoder1 did you see this issue?

What did you think about this?  Was just coming here to raise an issue to ask the same thing 😄

**Comment by gep13** [comment]
@nelsonwellswku as you will hopefully see, this repo has now moved under the cake-contrib organisation 😄
